edsr:
    scale: 4
    n_resblocks: 16
    n_feats: 64
    rgb_range: 255
    res_scale: 1
    n_colors: 3

batch_shape: [8, 3, 48, 48]
lr: 1.0e-4
lr_decay:
    method: multistep
    decay_step: [500]
    decay_rate: 0.1
